// Simulated demo fixtures for the marketing site.
//
// One scenario object drives both the Agent view and the API view of the single
// demo, so the two never tell different stories. Nothing here is fetched,
// generated by a model, or sent anywhere: the page renders these fixtures in the
// browser and says so.
//
// Rules this file follows, because the demo is the most-read description of the
// API that exists:
//   * a 202 receipt is never presented as a published post;
//   * a publication shows an external URL only when the fixture records one,
//     otherwise it shows the identifier the platform actually returns;
//   * an ambiguous failure keeps status failed with errorAmbiguous true and is
//     never presented as safe to resend automatically;
//   * a replayed request keeps the original result, and the same key with
//     different content is a conflict.

export type PlatformKey = "bluesky" | "threads" | "x" | "tumblr" | "linkedin";

/** Aggregate post status values the API documents. */
export type PostStatus = "queued" | "scheduled" | "publishing" | "published" | "partial" | "failed";

/** Publication status values the API documents. */
export type PublicationStatus = "pending" | "publishing" | "published" | "failed";

export type PublicationEntry = {
  platform: PlatformKey;
  status: PublicationStatus;
  /** Identifier the platform returned, when the fixture records one. */
  externalId?: string;
  /** Post link the platform returned. Only present when a real run would have one. */
  externalUrl?: string;
  /**
   * True when `externalUrl` is a placeholder used to show the shape of a result
   * link. The rendered row labels it so nobody reads it as a real post.
   */
  externalUrlIsExample?: boolean;
  errorCode?: string;
  errorMessage?: string;
  errorAmbiguous?: boolean;
  /** Plain-language note for the Agent view. */
  note?: string;
};

export type DemoResponseKind = "none" | "accepted" | "replayed" | "conflict";

/** What the API view shows in its receipt panel at a given step. */
export type DemoResponse = {
  kind: DemoResponseKind;
  label: string;
  body: string;
};

export type AgentPreview = {
  platform: PlatformKey;
  text: string;
};

/** One line in the Agent view's conversation. */
export type AgentTurn = {
  speaker: "you" | "agent";
  text: string;
  previews?: AgentPreview[];
};

export type DemoStep = {
  id: string;
  title: string;
  detail: string;
  /** Null until an accepted post exists; the API view says so explicitly. */
  postStatus: PostStatus | null;
  publications: PublicationEntry[];
  /** Shown in the API view's code panel when a step sends a different request. */
  request?: { note: string; body: string };
  response: DemoResponse;
  turn?: AgentTurn;
};

export type DemoScenarioId = "success" | "partial" | "ambiguous" | "replay";

export type DemoScenario = {
  id: DemoScenarioId;
  /** Picker label. Short enough for a narrow card. */
  label: string;
  summary: string;
  /** Post id used by the acceptance receipt and the status response. */
  postId: string;
  platforms: PlatformKey[];
  request: {
    path: string;
    idempotencyKey: string;
    body: string;
  };
  /** What the Agent view says about preview and confirmation ownership. */
  boundary: string;
  outcome: { headline: string; detail: string; tone: "ok" | "warn" | "danger" | "info" };
  /** What this scenario must not be read as permission to do. */
  caution: string;
  steps: DemoStep[];
};

const noResponse: DemoResponse = { kind: "none", label: "Nothing sent yet", body: "" };

const acceptedQueued: DemoResponse = {
  kind: "accepted",
  label: "POST /v1/posts",
  body: `HTTP/1.1 202 Accepted
{
  "id": "post_01J9ZK4W2Q",
  "status": "queued"
}`,
};

const replayedSameKey: DemoResponse = {
  kind: "replayed",
  label: "POST /v1/posts - same key, same body",
  body: `HTTP/1.1 200 OK
{
  "id": "post_01J9ZK5D8R",
  "status": "published",
  "replayed": true
}`,
};

const conflictDifferentBody: DemoResponse = {
  kind: "conflict",
  label: "POST /v1/posts - same key, edited text",
  body: `HTTP/1.1 409 Conflict
{
  "error": {
    "code": "IDEMPOTENCY_CONFLICT",
    "message": "Idempotency-Key was already used with a different request"
  }
}`,
};

/** The Bluesky post row in a finished success, used by two steps. */
const publishedBluesky: PublicationEntry = {
  platform: "bluesky",
  status: "published",
  externalId: "at://did:plc:example/app.bsky.feed.post/3k7demo",
  externalUrl: "https://example.com/demo/bluesky-post",
  externalUrlIsExample: true,
  errorAmbiguous: false,
  note: "Published with an id and a result link. The link in this fixture is an example URL, not a real post.",
};

const publishedThreads: PublicationEntry = {
  platform: "threads",
  status: "published",
  externalId: "17890000000000000",
  errorAmbiguous: false,
  note: "Published with a numeric id and no link.",
};

const previewThreads =
  "Syndroo 0.2.0-rc.1 candidate: one HTTP call accepts a post and queues one publication per platform. Live accounts are still pending.";

const previewBluesky =
  "Syndroo 0.2.0-rc.1 candidate: Mock SNS gate green for Bluesky and Threads. Live-account acceptance still pending.";

export const demoScenarios: DemoScenario[] = [
  {
    id: "success",
    label: "Publish a product update",
    summary: "Two platforms, one accepted request, and a per-platform result.",
    postId: "post_01J9ZK4W2Q",
    platforms: ["threads", "bluesky"],
    request: {
      path: "/v1/posts",
      idempotencyKey: "release-0.2.0-rc.1",
      body: `{
  "content": "${previewThreads}",
  "platforms": ["threads", "bluesky"],
  "overrides": {
    "bluesky": { "content": "${previewBluesky}" }
  }
}`,
    },
    boundary:
      "Drafting, the platform previews and the confirmation below happen in your agent or script. The API accepts a post; it has no preview or approval endpoint.",
    outcome: {
      headline: "Both platforms published",
      detail:
        "Acceptance is not delivery. The 202 receipt arrived first, and the per-platform results arrived afterwards.",
      tone: "ok",
    },
    caution:
      "Threads returned an id with no link, and Bluesky returned an id plus a link. Only the returned link is shown; none is constructed.",
    steps: [
      {
        id: "ask",
        title: "You ask for the update",
        detail: "A person, agent or script decides what should go out.",
        postStatus: null,
        publications: [],
        response: noResponse,
        turn: {
          speaker: "you",
          text: "Post today's release note to Threads and Bluesky. Bluesky needs the shorter version.",
        },
      },
      {
        id: "preview",
        title: "Preview and confirmation",
        detail:
          "The client shows both versions and waits for you. Nothing reaches the API before you confirm.",
        postStatus: null,
        publications: [],
        response: noResponse,
        turn: {
          speaker: "agent",
          text: "Two drafts ready. Confirm and I will send one request with a per-platform override.",
          previews: [
            { platform: "threads", text: previewThreads },
            { platform: "bluesky", text: previewBluesky },
          ],
        },
      },
      {
        id: "accepted",
        title: "Accepted, not confirmed",
        detail:
          "The Worker validates the request and stores one pending publication per platform. The reply is HTTP 202 with status queued: acceptance, not platform success.",
        postStatus: "queued",
        publications: [
          { platform: "threads", status: "pending" },
          { platform: "bluesky", status: "pending" },
        ],
        response: acceptedQueued,
        turn: {
          speaker: "agent",
          text: "Accepted: HTTP 202, status queued. Publishing is not confirmed yet.",
        },
      },
      {
        id: "publishing",
        title: "Queued work is claimed",
        detail: "A Queue consumer claims one publication and calls that platform once.",
        postStatus: "publishing",
        publications: [
          { platform: "threads", status: "publishing" },
          { platform: "bluesky", status: "publishing" },
        ],
        response: noResponse,
        turn: { speaker: "agent", text: "Both publications are in flight. Poll the post to watch each one." },
      },
      {
        id: "results",
        title: "Per-platform results",
        detail:
          "Both platforms confirmed. A post is published only when every publication succeeded.",
        postStatus: "published",
        publications: [publishedThreads, publishedBluesky],
        response: noResponse,
        turn: {
          speaker: "agent",
          text: "Published on both platforms. Threads returned an id only; Bluesky returned an id and a post link.",
        },
      },
    ],
  },
  {
    id: "partial",
    label: "One platform fails",
    summary: "Two platforms published, one hit a rate limit, and one post is partial.",
    postId: "post_01J9ZK9F1B",
    platforms: ["bluesky", "threads", "x"],
    request: {
      path: "/v1/posts",
      idempotencyKey: "nightly-ingest-2291",
      body: `{
  "content": "Nightly ingest finished: 41,208 rows reconciled, 0 quarantined records.",
  "platforms": ["bluesky", "threads", "x"]
}`,
    },
    boundary:
      "The client prepared this text from the finished job. The API accepts posts; it does not read your job logs or generate the summary.",
    outcome: {
      headline: "Partial: two published, one failing",
      detail:
        "The post status is partial and each publication keeps its own status. The published platforms must not be sent again.",
      tone: "warn",
    },
    caution:
      "There is no retry endpoint. Sending the whole request again would duplicate the platforms that already published, so a new request must be a separate decision and must target only the platform that failed.",
    steps: [
      {
        id: "preview",
        title: "Job summary prepared",
        detail: "The automation writes the summary and confirms it is safe to publish.",
        postStatus: null,
        publications: [],
        response: noResponse,
        turn: {
          speaker: "agent",
          text: "Nightly job finished. Sending the same summary to three platforms.",
          previews: [
            {
              platform: "bluesky",
              text: "Nightly ingest finished: 41,208 rows reconciled, 0 quarantined records.",
            },
            {
              platform: "x",
              text: "Nightly ingest: 41,208 rows reconciled, 0 quarantined. Full report in the run log.",
            },
          ],
        },
      },
      {
        id: "accepted",
        title: "Accepted",
        detail: "One request, three pending publications, HTTP 202 with status queued.",
        postStatus: "queued",
        publications: [
          { platform: "bluesky", status: "pending" },
          { platform: "threads", status: "pending" },
          { platform: "x", status: "pending" },
        ],
        response: {
          kind: "accepted",
          label: "POST /v1/posts",
          body: `HTTP/1.1 202 Accepted
{
  "id": "post_01J9ZK9F1B",
  "status": "queued"
}`,
        },
        turn: { speaker: "agent", text: "Accepted: HTTP 202, status queued." },
      },
      {
        id: "publishing",
        title: "Publishing",
        detail: "Each publication is claimed and called separately, so one failure does not stop the others.",
        postStatus: "publishing",
        publications: [
          { platform: "bluesky", status: "publishing" },
          { platform: "threads", status: "publishing" },
          { platform: "x", status: "publishing" },
        ],
        response: noResponse,
        turn: { speaker: "agent", text: "Three platform calls in flight." },
      },
      {
        id: "results",
        title: "One platform fails",
        detail:
          "Bluesky and X published. Threads hit a rate limit, and the retries that followed all failed, so the third and final attempt exhausted the retry budget and the publication is terminal.",
        postStatus: "partial",
        publications: [
          publishedBluesky,
          {
            platform: "x",
            status: "published",
            externalId: "1800000000000000002",
            errorAmbiguous: false,
            note: "Published.",
          },
          {
            platform: "threads",
            status: "failed",
            errorCode: "RATE_LIMIT",
            errorMessage: "Threads rate limit persisted across the three allowed attempts",
            errorAmbiguous: false,
            note: "Terminal after three attempts. Only this publication may be retried, and only by a human or a new request.",
          },
        ],
        response: noResponse,
        turn: {
          speaker: "agent",
          text: "Bluesky and X published. Threads stopped after its third attempt; the other two must not be sent again.",
        },
      },
    ],
  },
  {
    id: "ambiguous",
    label: "Timeout, outcome unknown",
    summary: "A timed-out write stays failed and ambiguous instead of being resent.",
    postId: "post_01J9ZK7P4C",
    platforms: ["threads"],
    request: {
      path: "/v1/posts",
      idempotencyKey: "status-page-note-004",
      body: `{
  "content": "Scheduled maintenance is finished; the publishing API is accepting posts again.",
  "platforms": ["threads"]
}`,
    },
    boundary:
      "The client proposed the sentence. The API publishes or fails; it never retries an unknown outcome for you.",
    outcome: {
      headline: "Failed and ambiguous",
      detail:
        "The request reached the platform and then timed out, so the post may exist. Syndroo records status failed with errorAmbiguous true and does not resend it.",
      tone: "danger",
    },
    caution:
      "Check the platform by hand before publishing again, because an automatic resend can create a second post.",
    steps: [
      {
        id: "preview",
        title: "Message prepared",
        detail: "One platform, one sentence, one idempotency key.",
        postStatus: null,
        publications: [],
        response: noResponse,
        turn: { speaker: "you", text: "Tell Threads that maintenance is over." },
      },
      {
        id: "accepted",
        title: "Accepted",
        detail: "The post is queued like any other. Acceptance still says nothing about delivery.",
        postStatus: "queued",
        publications: [{ platform: "threads", status: "pending" }],
        response: {
          kind: "accepted",
          label: "POST /v1/posts",
          body: `HTTP/1.1 202 Accepted
{
  "id": "post_01J9ZK7P4C",
  "status": "queued"
}`,
        },
        turn: { speaker: "agent", text: "Accepted: HTTP 202, status queued." },
      },
      {
        id: "timeout",
        title: "The platform call times out",
        detail:
          "The request reached the platform and the response never arrived, so the outcome is unknown rather than failed.",
        postStatus: "publishing",
        publications: [{ platform: "threads", status: "publishing" }],
        response: noResponse,
        turn: { speaker: "agent", text: "Waiting for Threads. The adapter has a bounded deadline." },
      },
      {
        id: "ambiguous",
        title: "Recorded as failed and ambiguous",
        detail:
          "Publication status is failed with errorCode NETWORK and errorAmbiguous true. Syndroo stops here and asks a person to check.",
        postStatus: "failed",
        publications: [
          {
            platform: "threads",
            status: "failed",
            errorCode: "NETWORK",
            errorMessage: "Request timed out after the platform call started",
            errorAmbiguous: true,
            note: "May have published. Verify on the platform before doing anything else.",
          },
        ],
        response: noResponse,
        turn: {
          speaker: "agent",
          text: "Unknown outcome on Threads: the post may exist. Open Threads and check before retrying anything.",
        },
      },
    ],
  },
  {
    id: "replay",
    label: "Same key, one result",
    summary: "A repeated request returns the original result; edited text gets a 409.",
    postId: "post_01J9ZK5D8R",
    platforms: ["bluesky"],
    request: {
      path: "/v1/posts",
      idempotencyKey: "deploy-notice-118",
      body: `{
  "content": "Deploy 118 is live: queue retries now respect an explicit deadline.",
  "platforms": ["bluesky"]
}`,
    },
    boundary:
      "The retry below is a client decision. The API only needs the same idempotency key with the same body.",
    outcome: {
      headline: "Replay returns the original result",
      detail:
        "The same key with the same body returns the stored post with replayed true. The same key with different content returns 409 IDEMPOTENCY_CONFLICT.",
      tone: "info",
    },
    caution:
      "Use one key for exactly one logical post. A key reused across different text is a conflict, not an update.",
    steps: [
      {
        id: "preview",
        title: "Text confirmed",
        detail: "One platform, one key, one logical post that will be retried if the first call is lost.",
        postStatus: null,
        publications: [],
        response: noResponse,
        turn: { speaker: "agent", text: "Deploy notice ready for Bluesky with a stable idempotency key." },
      },
      {
        id: "accepted",
        title: "Accepted",
        detail: "The key is stored with the post, so a repeat of the same body is answered from the stored result.",
        postStatus: "queued",
        publications: [{ platform: "bluesky", status: "pending" }],
        response: {
          kind: "accepted",
          label: "POST /v1/posts",
          body: `HTTP/1.1 202 Accepted
{
  "id": "post_01J9ZK5D8R",
  "status": "queued"
}`,
        },
        turn: { speaker: "agent", text: "Accepted: HTTP 202, status queued." },
      },
      {
        id: "published",
        title: "Published",
        detail: "The publication succeeded, and the stored result is what a replay will return.",
        postStatus: "published",
        publications: [publishedBluesky],
        response: noResponse,
        turn: { speaker: "agent", text: "Published on Bluesky." },
      },
      {
        id: "replay",
        title: "The client retries the same request",
        detail:
          "Identical body and key. The API returns the original post with HTTP 200 and replayed true instead of publishing again.",
        postStatus: "published",
        publications: [publishedBluesky],
        response: replayedSameKey,
        turn: {
          speaker: "agent",
          text: "The identical retry was answered from the stored result instead of being published again.",
        },
      },
      {
        id: "conflict",
        title: "The same key with edited text",
        detail:
          "The key is already bound to a different request, so the API refuses with HTTP 409 and IDEMPOTENCY_CONFLICT.",
        postStatus: "published",
        publications: [publishedBluesky],
        request: {
          note: "Same key, edited text",
          body: `{
  "content": "Deploy 118 is live, and the queue deadline change shipped with it.",
  "platforms": ["bluesky"]
}`,
        },
        response: conflictDifferentBody,
        turn: {
          speaker: "agent",
          text: "Rejected: that key belongs to the earlier text. A genuinely different post needs a new key.",
        },
      },
    ],
  },
];
